[package]
name = "lbp2900-rust"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "GPL-3.0-or-later"
publish = false
autobins = false
build = "build.rs"

[features]
default = []
cups = []

[[bin]]
name = "rastertocapt-lbp2900-rust"
path = "src/bin/filter.rs"
required-features = ["cups"]

[profile.release]
overflow-checks = true
panic = "abort"
lto = "thin"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
undocumented_unsafe_blocks = "deny"
